[project]
protostar-version = "0.9.1"
lib-path = "lib"
cairo-path = [
    "./lib/cairo_contracts/src"
]

[contracts]
selfie_pool = ["src/selfie/SelfiePool.cairo"]
simple_governance = ["src/selfie/SimpleGovernance.cairo"]



[test]
disable-hint-validation = true
